export const PLACEHOLDER_OPERATOR_NAME = "PLACEHOLDER_OPERATOR_NAME";
export const PLACEHOLDER_OPERATOR_ADDRESS = "PLACEHOLDER_OPERATOR_ADDRESS";
export const PLACEHOLDER_OPERATOR_EMAIL = "PLACEHOLDER_OPERATOR_EMAIL";

export function hasLegalPlaceholders(): boolean {
  return (
    PLACEHOLDER_OPERATOR_NAME.startsWith("PLACEHOLDER_") ||
    PLACEHOLDER_OPERATOR_ADDRESS.startsWith("PLACEHOLDER_") ||
    PLACEHOLDER_OPERATOR_EMAIL.startsWith("PLACEHOLDER_")
  );
}
